name: tests & formatting
on: 
  push:
  pull_request:
    types: [opened]
  workflow_dispatch:
env:
  GCP_PROJECT: latestbit
  GCP_PROJECT_ID: 288860578009
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Authenticate to Google Cloud development
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/${{ env.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/lb-github-identity-pool/providers/lb-github-identity-pool-provider'
          service_account: 'lb-github-service-account@${{ env.GCP_PROJECT }}.iam.gserviceaccount.com'
          create_credentials_file: true
          access_token_lifetime: '240s'
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v1
      - run: cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test
